import os
def limpar_tela():
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')
option = ''
option_clt = ''
while option != "0":
  limpar_tela()
  print("|==========================================|")
  print("|=========== Gestão de clientes ===========|")
  print("|==========================================|")
  print("|==                                      ==|")
  print("|==        1-Módulo Clientes             ==|")
  print("|==                                      ==|")
  print("|==        2-Módulo Contas               ==|")
  print("|==                                      ==|")
  print("|==        3-Módulo Pagamentos           ==|")
  print("|==                                      ==|")
  print("|==        4-Módulo de informações       ==|")
  print("|==                                      ==|")
  print("|==        0-Sair                        ==|")
  print("|==                                      ==|")
  print("|==========================================|")
  print("|==========================================|")
  option = input("|= Escolha uma opção: ")
  if option == "1":
    option_clt = ''
    while option_clt != "0":
        limpar_tela()
        print("|==========================================|")
        print("|=========== Módulo de Clientes ===========|")
        print("|==========================================|")
        print("|==                                      ==|")
        print("|==        1-Cadastrar clientes          ==|")
        print("|==                                      ==|")
        print("|==        2-Buscar clientes             ==|")
        print("|==                                      ==|")
        print("|==        3-Editar clientes             ==|")
        print("|==                                      ==|")
        print("|==        4-Remover clientes            ==|")
        print("|==                                      ==|")
        print("|==        0-Sair                        ==|")
        print("|==                                      ==|")
        print("|==========================================|")
        print("|==========================================|")
        option_clt = input("|= Escolha uma opção: ")
        if option_clt == "1":
            nome_clt = input("|= Digite o nome do cliente: ")
            print("|=")
            phone_clt = input("|= Digite o telefone do cliente: ")
            print("|=")
            cpf_clt = input("|= Digite o CPF do cliente: ")
            print("|=")
            city_clt = input("|= Digite a cidade do cliente: ")
            print("|==========================================|")
            print("|==                                      ==|")
            print("|==   Cliente cadastrado com sucesso!!   ==|")
            print("|==                                      ==|")
            print("|==========================================|")
            input("|= Voltar para o Módulo de clientes <Enter>: ")
        elif option_clt == "2":
            nome_clt = input("|= Digite o nome do cliente: ")
            print("|==========================================|")
            print("|==                                      ==|")
            print("|==   Cliente encontrado com sucesso!!   ==|")
            print("|==                                      ==|")
            print("|==========================================|")
            input("|= Voltar para o Módulo de clientes <Enter>: ")
        elif option_clt == "3":
            option3_clt = '' 
            while option3_clt != "0":
                limpar_tela()
                nome_clt = input("|= Digite o nome do cliente: ")
                print("|==========================================|")
                print("|============= Editar cliente =============|")
                print("|==========================================|")
                print("|==                                      ==|")
                print("|==        1-Editar nome                 ==|")
                print("|==                                      ==|")
                print("|==        2-Editar telefone             ==|")
                print("|==                                      ==|")
                print("|==        3-Editar CPF                  ==|")
                print("|==                                      ==|")
                print("|==        4-Editar cidade               ==|")
                print("|==                                      ==|")
                print("|==        0-Sair                        ==|")
                print("|==                                      ==|")
                print("|==========================================|")
                print("|==========================================|")
                option3_clt = input("|= Escolha uma opção: ")
                if option3_clt == "1":
                   nome_clt = input("|= Digite o nome do cliente: ")
                elif option3_clt == "2":
                   phone_clt = input("|= Digite o telefone do cliente: ")
                elif option3_clt == "3":
                   cpf_clt = input("|= Digite o CPF do cliente: ")
                elif option3_clt == "4":
                   city_clt = input("|= Digite a cidade do cliente: ")
                else:
                   print()
        elif option_clt == "4":
            nome_clt = input("|= Digite o nome do cliente: ")
            print("|==========================================|")
            print("|==                                      ==|")
            print("|==   Cliente removido com sucesso!!     ==|")
            print("|==                                      ==|")
            print("|==========================================|")
            input("|= Voltar para o Módulo de clientes <Enter>: ")
        elif not option_clt:
           print()
        else:
           option_clt = "0"
  elif option == "2":
    option_cnt = ''
    while option_cnt != "0":
        limpar_tela()
        print("|==========================================|")
        print("|============ Módulo de Contas ============|")
        print("|==========================================|")
        print("|==                                      ==|")
        print("|==     1-Adicionar débitos a conta      ==|")
        print("|==                                      ==|")
        print("|==     2-Buscar contas do cliente       ==|")
        print("|==                                      ==|")
        print("|==     3-Remover débito de conta        ==|")
        print("|==                                      ==|")
        print("|==     3-Editar valores de uma conta    ==|")
        print("|==                                      ==|")
        print("|==     0-Sair                           ==|")
        print("|==                                      ==|")
        print("|==========================================|")
        print("|==========================================|")
        option_cnt = input("|= Escolha uma opção: ")
        if option_cnt == "0":
           print()
        else:
            print("|==========================================|")
            print("|==========================================|")
            print("|==                                      ==|")
            print("|==       Módulo em desenvolvimento      ==|")
            print("|==                                      ==|")
            print("|==========================================|")
            print("|==========================================|")
            input("|= Voltar para o Módulo de contas <Enter>: ")

  elif option == "3":
    option_pmt = ''
    while option_pmt != "0":
        limpar_tela()
        print("|==========================================|")
        print("|========== Módulo de Pagamentos ==========|")
        print("|==========================================|")
        print("|==                                      ==|")
        print("|==     1-Registrar pagamentos           ==|")
        print("|==                                      ==|")
        print("|==     2-Ver histórico de pagamento     ==|")
        print("|==                                      ==|")
        print("|==     3-Remover registros              ==|")
        print("|==                                      ==|")
        print("|==     3-Editar registros               ==|")
        print("|==                                      ==|")
        print("|==     0-Sair                           ==|")
        print("|==                                      ==|")
        print("|==========================================|")
        print("|==========================================|")
        option_pmt = input("|= Escolha uma opção: ")
        if option_pmt == "0":
           print()
        else:
            print("|==========================================|")
            print("|==========================================|")
            print("|==                                      ==|")
            print("|==       Módulo em desenvolvimento      ==|")
            print("|==                                      ==|")
            print("|==========================================|")
            print("|==========================================|")
            input("|= Voltar para o Módulo de pagamentos <Enter>: ")
  elif option == "4":
    limpar_tela()
    print("|==========================================|")
    print("|========== Módulo de Informações =========|")
    print("|==========================================|")
    print("|==                                      ==|")
    print("|==     Projeto de Gestão de Clientes    ==|")
    print("|==                                      ==|")
    print("|==     Autor do projeto:                ==|")
    print("|==     ↳ Francisco Talismar             ==|")
    print("|==                                      ==|")
    print("|==     Licença Pública Geral GNU        ==|")
    print("|==     ↳ www.gnu.org/licenses/gpl.html  ==|")
    print("|==                                      ==|")
    print("|==========================================|")
    print("|==========================================|")
    option_inv = input("|= Voltar para o Módulo principal <Enter>: ")
  elif not option:
     print()
  elif option == "0":
     fechar = input("|= Tem certeza que deseja sair? (S/N): ")
     if fechar.upper() == "S":
        limpar_tela()
        print("Fim do programa!!")    
     else:
        option = ''
  else:
    limpar_tela()
    print("|==========================================|")
    print("|==========================================|")
    print("|==                                      ==|")
    print("|==           Opção inválida!!           ==|")
    print("|==                                      ==|")
    print("|==========================================|")
    print("|==========================================|")
    option_inv = input("|= Voltar para o Módulo principal <Enter>: ")